From ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    screenfetch \
    iputils-ping \
    vim \
    htop \
    tmux \
    wget \
    curl \
    git \
    ssh && \
    rm -rf /var/lib/apt/lists/*

# RUN useradd -mr mlento
# USER mlento
# WORKDIR /home/mlento
